# Generated by Django 4.2.2 on 2023-06-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('lieu_residence', models.CharField(max_length=100)),
                ('numero_telephone', models.IntegerField(max_length=20)),
            ],
        ),
    ]
