# Generated by Django 4.2.2 on 2023-06-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cni', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=20)),
                ('date_naissance', models.DateTimeField(verbose_name='date published')),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('endroit_trouver', models.CharField(max_length=20)),
            ],
        ),
    ]
