# Generated by Django 4.2.3 on 2023-07-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_carte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cni', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=20)),
                ('date_naissance', models.CharField(max_length=10)),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('endroit_trouver', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
