# Generated by Django 4.2.3 on 2023-07-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_cartes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartes',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='cartes',
            name='lieu_naissance',
        ),
        migrations.RemoveField(
            model_name='cartes',
            name='prenom',
        ),
        migrations.AddField(
            model_name='cartes',
            name='photo1',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
