# Generated by Django 4.2.3 on 2023-07-27 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_cartes_date_naissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartes',
            name='publieur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.utilisateur'),
        ),
    ]
